#!/bin/bash -l
if [ -z "$*" ] || [ "$1" == "--help" ] ; then
	echo "Helper script to run or manage an irc3 bot."
	echo "Usage: $(basename "$0") CONFIGURATION [OPTION]..."
	echo
	echo "CONFIGURATION: Name of the configuration file (may omit the .ini)."
	echo
	echo "OPTION:        Are forwared to irc3 unless the first option is:"
	echo "  --logs       Shows the bot's latest logs (with tail)"
	echo "  --reload     Reloads the bot (SIGHUP)"
	echo "  --kill       Kills the bot"
	echo "  --test       Starts the bot in test mode (DEBUG logs to STDOUT)"
	echo
	echo "This script creates a lock, so multiple execution will be prevented."
	exit
fi

set -e
which irc3 >/dev/null || { echo "Could not find irc3 in path." 1>&2; exit 1; }
cd "$(dirname "$(readlink -f "$0")")"

CONFIG="${1%.ini}"
test -n "${CONFIG}" || { echo "No configuration specified." 1>&2; exit 1; }
test -f "${CONFIG}.ini" || { echo "Configuration not found." 1>&2; exit 1; }
shift

case "$1" in
	"--logs")
		cd logs
		shift
		tail "$@" "${CONFIG}"/*.log \
		| egrep --color '^|^==> .* <==$'
		echo
		;;
	"--reload")
		pgrep -f "\\b$(basename "$0") ${CONFIG}(\.ini)?\\b" \
		| while read P; do pkill -x irc3 -P "$P" -HUP -e || :; done \
		| sed 's/kill/reload/g'
		;;
	"--kill")
		pgrep -f "\\b$(basename "$0") ${CONFIG}(\.ini)?\\b" \
		| while read P; do pkill -x irc3 -P "$P" -e || :; done
		;;
	"--test")
		shift
		irc3 --verbose --debug --raw --logdate "$@" "${CONFIG}.ini"
		;;
	*)
		exec 2>&1
		mkdir -p "logs/${CONFIG}"
		exec 200>"logs/${CONFIG}/$(basename "$0").lock"
		flock -n 200 || exit 2
		find "logs/${CONFIG}/" -name 'messages.*' -print0 | xargs -0r rm -rf

		exec &>"logs/${CONFIG}/out.log"
		tty -s && exec &> >(tee "logs/${CONFIG}/out.log")
		irc3 --logdir "logs/${CONFIG}/" "$@" "${CONFIG}.ini" \
		;;
esac
