name: Dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_AUTHOR: mentalfs
  IMAGE_NAME: boinc-client
  TAG: latest

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    if: ${{ github.actor == 'dependabot[bot]' }}
    with:
      push: false
    secrets: inherit

  automerge:
    needs: [docker]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-push:
    needs: [automerge]
    uses: ./.github/workflows/docker.yml
    if: ${{ github.actor == 'dependabot[bot]' }}
    with:
      push: ${{ github.ref != 'refs/heads/main' }}
    secrets: inherit
