name: Docker Prune

on:
  schedule:
    - cron: '15 18 * * *'

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
    - name: Prune images older than 7 days
      uses: vlaurin/action-ghcr-prune@v0.5.0
      with:
        token: ${{ secrets.PACKAGE_DELETE_TOKEN }}
        user: mentalfs
        container: irc3-twitch
        dry-run: false
        keep-younger-than: 7 # days
        keep-last: 2
        prune-untagged: true
