name: Push
on: push

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    if: ${{ github.actor != 'dependabot[bot]' }}
    with:
      push: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
